---
Resources:
  AdditionalHydraTestPermissions:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - Ref: 'HydraTestInvocationRole'
      PolicyName: 'AdditionalHydraTestPermissions'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "cloudformation:DescribeStacks"
            Resource: "*"
          -
            Effect: "Allow"
            Action:
              - "execute-api:Invoke"
            Resource:
              {"Fn::Sub": ["arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${LambdaApiId}/${LambdaApiStage}/*", {'LambdaApiId': {Ref: 'LambdaAPIDefinition'}, 'LambdaApiStage': {Ref: 'LambdaAPIDefinitionStage'}}]}
