//package com.amazon.ata.primeclubservice;
//
//import com.amazon.coral.model.xml.*;
//import com.amazon.coral.model.*;
//import com.amazon.coral.util.CharSequenceReader;
//
//public class ModelIndexFactory implements com.amazon.coral.model.ModelIndexFactory {
//
//  private final ModelIndex modelIndex;
//
//  public ModelIndex newModelIndex() {
//    return modelIndex;
//  }
//
//
//  public ModelIndexFactory() {
//    StringBuilder source = new StringBuilder();
//
//    _assemble$1(source);
//
//    SourceReader reader = new SourceReader("com.amazon.ata.primeclubservice.ModelIndexFactory", new CharSequenceReader(source));
//    this.modelIndex = new DefaultModelIndexFactory(new XmlModelIndexFactory(reader)).newModelIndex();
//  }
//
//  private static void _assemble$1(StringBuilder source) {
//    source.append("<definition assembly=\"contents.fully.qualified\" version=\"1.0\">\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.primeclubservice#stringValue\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#stringValue\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#stringValue\">\n");
//    source.append("    <name value=\"stringValue\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("    <name value=\"benefitType\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("    <name value=\"benefitType\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("    <name value=\"benefitType\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitType\">\n");
//    source.append("    <name value=\"benefitType\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <service name=\"com.amazon.ata.primeclubservice#ATAPrimeClubService\">\n");
//    source.append("    <operation target=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\"/>\n");
//    source.append("  </service>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#ATAPrimeClubService\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.ATAPrimeClubService\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.primeclubservice#ATAPrimeClubService\"><![CDATA[\n");
//    source.append("        ATA Fake of the PrimeClubService to be used in learning projects.\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#ATAPrimeClubService\">\n");
//    source.append("    <name value=\"ATAPrimeClubService\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <member name=\"customerId\" target=\"com.amazon.ata.primeclubservice#stringValue\"/>\n");
//    source.append("    <member name=\"marketplaceId\" target=\"com.amazon.ata.primeclubservice#stringValue\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.GetPrimeBenefitsRequest\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.GetPrimeBenefitsRequest\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <class value=\"GetPrimeBenefitsRequest:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\">\n");
//    source.append("    <name value=\"GetPrimeBenefitsRequest\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <httplabel target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <label value=\"customerId\"/>\n");
//    source.append("  </httplabel>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.primeclubservice#BenefitLevel\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <enum target=\"com.amazon.ata.primeclubservice#BenefitLevel\">    <enumValue value=\"MINI\" name=\"MINI\"/>    <enumValue value=\"STANDARD\" name=\"STANDARD\"/>    <enumValue value=\"PLUS\" name=\"PLUS\"/>    <enumValue value=\"FRESH\" name=\"FRESH\"/>  </enum>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#BenefitLevel\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <enumjava target=\"com.amazon.ata.primeclubservice#BenefitLevel\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.BenefitLevel\"/>\n");
//    source.append("  </enumjava>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#BenefitLevel\">\n");
//    source.append("    <name value=\"BenefitLevel\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <httplabel target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <label value=\"marketplaceId\"/>\n");
//    source.append("  </httplabel>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <member name=\"benefitLevel\" target=\"com.amazon.ata.primeclubservice#BenefitLevel\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.BenefitMetadata\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.BenefitMetadata\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <class value=\"BenefitMetadata:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <name value=\"BenefitMetadata\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <list name=\"com.amazon.ata.primeclubservice#PrimeBenefitsList\">\n");
//    source.append("    <member target=\"com.amazon.ata.primeclubservice#PrimeBenefit\"/>\n");
//    source.append("  </list>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#PrimeBenefitsList\">\n");
//    source.append("    <class value=\"java.util.List\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#PrimeBenefitsList\">\n");
//    source.append("    <name value=\"PrimeBenefitsList\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\" isa=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <member name=\"noOfDiscOut\" target=\"com.amazon.ata.primeclubservice#longValue\"/>\n");
//    source.append("    <member name=\"monthlyLimit\" target=\"com.amazon.ata.primeclubservice#longValue\"/>\n");
//    source.append("    <member name=\"billingSchedule\" target=\"com.amazon.ata.primeclubservice#stringValue\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.DVDRentalBenefitMetadata\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.DVDRentalBenefitMetadata\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\">\n");
//    source.append("    <class value=\"DVDRentalBenefitMetadata:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata\">\n");
//    source.append("    <name value=\"DVDRentalBenefitMetadata\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$monthlyLimit\">\n");
//    source.append("    <name value=\"monthlyLimit\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$monthlyLimit\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$monthlyLimit\">\n");
//    source.append("    <name value=\"monthlyLimit\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$monthlyLimit\">\n");
//    source.append("    <name value=\"monthlyLimit\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$monthlyLimit\">\n");
//    source.append("    <name value=\"monthlyLimit\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse$primeBenefits\">\n");
//    source.append("    <name value=\"primeBenefits\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse$primeBenefits\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse$primeBenefits\">\n");
//    source.append("    <name value=\"primeBenefits\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse$primeBenefits\">\n");
//    source.append("    <name value=\"primeBenefits\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse$primeBenefits\">\n");
//    source.append("    <name value=\"primeBenefits\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <long name=\"com.amazon.ata.primeclubservice#longValue\"/>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#longValue\">\n");
//    source.append("    <class value=\"long\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#longValue\">\n");
//    source.append("    <name value=\"longValue\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#ClientFaultException$message\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"Message\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.primeclubservice#Benefit\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <enum target=\"com.amazon.ata.primeclubservice#Benefit\">    <enumValue value=\"MOM_LITE\" name=\"MOM_LITE\"/>    <enumValue value=\"MOM_DISCOUNT\" name=\"MOM_DISCOUNT\"/>    <enumValue value=\"FREE_TRIDENT_VOD\" name=\"FREE_TRIDENT_VOD\"/>    <enumValue value=\"FREE_EXPEDITED_SHIPPING\" name=\"FREE_EXPEDITED_SHIPPING\"/>    <enumValue value=\"DIM_SUM\" name=\"DIM_SUM\"/>    <enumValue value=\"AMZN4KIDS\" name=\"AMZN4KIDS\"/>  </enum>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#Benefit\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <enumjava target=\"com.amazon.ata.primeclubservice#Benefit\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.Benefit\"/>\n");
//    source.append("  </enumjava>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#Benefit\">\n");
//    source.append("    <name value=\"Benefit\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <operation name=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\">\n");
//    source.append("    <input target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsRequest\"/>\n");
//    source.append("    <output target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.primeclubservice#DependencyException\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.primeclubservice#InvalidParameterException\"/>\n");
//    source.append("  </operation>\n");
//    source.append("\n");
//    source.append("  <http target=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\">\n");
//    source.append("    <httpresponsecode value=\"200\"/>\n");
//    source.append("    <verb value=\"GET\"/>\n");
//    source.append("    <uri value=\"benefits/{marketplaceId}/{customerId}\"/>\n");
//    source.append("  </http>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\"><![CDATA[\n");
//    source.append("        This API determines what benefits a given customerID is receiving in a specific marketplaceID.\n");
//    source.append("        For all valid customerIds, it will always return a BenefitList. For customerIds that are not Prime,\n");
//    source.append("        this BenefitList will be empty.\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.GetPrimeBenefitsActivity\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefits\">\n");
//    source.append("    <name value=\"GetPrimeBenefits\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#ClientFaultException\" abstract=\"true\">\n");
//    source.append("    <member name=\"message\" target=\"com.amazon.ata.primeclubservice#errorMessage\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.ClientFaultException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.ClientFaultException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <type value=\"BadArgs\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <class value=\"ClientFaultException:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("    <name value=\"ClientFaultException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.primeclubservice#errorMessage\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#errorMessage\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#errorMessage\">\n");
//    source.append("    <name value=\"errorMessage\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#PrimeBenefitsList$member\">\n");
//    source.append("    <name value=\"member\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#PrimeBenefitsList$member\">\n");
//    source.append("    <name value=\"member\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$amountOfBooksAvailable\">\n");
//    source.append("    <name value=\"amountOfBooksAvailable\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$amountOfBooksAvailable\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$amountOfBooksAvailable\">\n");
//    source.append("    <name value=\"amountOfBooksAvailable\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$amountOfBooksAvailable\">\n");
//    source.append("    <name value=\"amountOfBooksAvailable\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$amountOfBooksAvailable\">\n");
//    source.append("    <name value=\"amountOfBooksAvailable\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$checkoutsPerMonth\">\n");
//    source.append("    <name value=\"checkoutsPerMonth\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$checkoutsPerMonth\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$checkoutsPerMonth\">\n");
//    source.append("    <name value=\"checkoutsPerMonth\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$checkoutsPerMonth\">\n");
//    source.append("    <name value=\"checkoutsPerMonth\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata$checkoutsPerMonth\">\n");
//    source.append("    <name value=\"checkoutsPerMonth\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\" isa=\"com.amazon.ata.primeclubservice#BenefitMetadata\">\n");
//    source.append("    <member name=\"amountOfBooksAvailable\" target=\"com.amazon.ata.primeclubservice#longValue\"/>\n");
//    source.append("    <member name=\"checkoutsPerMonth\" target=\"com.amazon.ata.primeclubservice#longValue\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.DimSumBenefitMetadata\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.DimSumBenefitMetadata\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\">\n");
//    source.append("    <class value=\"DimSumBenefitMetadata:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DimSumBenefitMetadata\">\n");
//    source.append("    <name value=\"DimSumBenefitMetadata\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <member name=\"primeBenefits\" target=\"com.amazon.ata.primeclubservice#PrimeBenefitsList\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.GetPrimeBenefitsResponse\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.GetPrimeBenefitsResponse\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <class value=\"GetPrimeBenefitsResponse:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#GetPrimeBenefitsResponse\">\n");
//    source.append("    <name value=\"GetPrimeBenefitsResponse\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <member name=\"benefitType\" target=\"com.amazon.ata.primeclubservice#Benefit\"/>\n");
//    source.append("    <member name=\"benefitMetadata\" target=\"com.amazon.ata.primeclubservice#BenefitMetadata\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.PrimeBenefit\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.PrimeBenefit\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <class value=\"PrimeBenefit:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#PrimeBenefit\">\n");
//    source.append("    <name value=\"PrimeBenefit\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#InvalidParameterException\" isa=\"com.amazon.ata.primeclubservice#ClientFaultException\">\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.InvalidParameterException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.InvalidParameterException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <type value=\"BadArgs\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"InvalidParameterException:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#InvalidParameterException\">\n");
//    source.append("    <name value=\"InvalidParameterException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DependencyException$message\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DependencyException$message\">\n");
//    source.append("    <name value=\"Message\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$noOfDiscOut\">\n");
//    source.append("    <name value=\"noOfDiscOut\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$noOfDiscOut\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$noOfDiscOut\">\n");
//    source.append("    <name value=\"noOfDiscOut\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$noOfDiscOut\">\n");
//    source.append("    <name value=\"noOfDiscOut\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$noOfDiscOut\">\n");
//    source.append("    <name value=\"noOfDiscOut\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#BenefitMetadata$benefitLevel\">\n");
//    source.append("    <name value=\"benefitLevel\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#BenefitMetadata$benefitLevel\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#BenefitMetadata$benefitLevel\">\n");
//    source.append("    <name value=\"benefitLevel\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#BenefitMetadata$benefitLevel\">\n");
//    source.append("    <name value=\"benefitLevel\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#BenefitMetadata$benefitLevel\">\n");
//    source.append("    <name value=\"benefitLevel\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <member name=\"message\" target=\"com.amazon.ata.primeclubservice#errorMessage\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <fault target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("  </fault>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <class value=\"com.amazon.ata.primeclubservice.DependencyException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <class value=\"amazon.ata.primeclubservice.DependencyException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.primeclubservice#DependencyException\"><![CDATA[\n");
//    source.append("        This exception is thrown on a database (or other dependency) error\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <type value=\"ServiceFailure\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <class value=\"DependencyException:http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DependencyException\">\n");
//    source.append("    <name value=\"DependencyException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitMetadata\">\n");
//    source.append("    <name value=\"benefitMetadata\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitMetadata\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitMetadata\">\n");
//    source.append("    <name value=\"benefitMetadata\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitMetadata\">\n");
//    source.append("    <name value=\"benefitMetadata\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#PrimeBenefit$benefitMetadata\">\n");
//    source.append("    <name value=\"benefitMetadata\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$billingSchedule\">\n");
//    source.append("    <name value=\"billingSchedule\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$billingSchedule\">\n");
//    source.append("    <order value=\"2\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$billingSchedule\">\n");
//    source.append("    <name value=\"billingSchedule\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.primeclubservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$billingSchedule\">\n");
//    source.append("    <name value=\"billingSchedule\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.primeclubservice#DVDRentalBenefitMetadata$billingSchedule\">\n");
//    source.append("    <name value=\"billingSchedule\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("</definition>");
//  }
//
//}
