//package com.amazon.ata.customerservice;
//
//import com.amazon.coral.model.xml.*;
//import com.amazon.coral.model.*;
//import com.amazon.coral.util.CharSequenceReader;
//
//public class ModelIndexFactory implements com.amazon.coral.model.ModelIndexFactory {
//
//  private final ModelIndex modelIndex;
//
//  public ModelIndex newModelIndex() {
//    return modelIndex;
//  }
//
//
//  public ModelIndexFactory() {
//    StringBuilder source = new StringBuilder();
//
//    _assemble$1(source);
//    _assemble$2(source);
//
//    SourceReader reader = new SourceReader("com.amazon.ata.customerservice.ModelIndexFactory", new CharSequenceReader(source));
//    this.modelIndex = new DefaultModelIndexFactory(new XmlModelIndexFactory(reader)).newModelIndex();
//  }
//
//  private static void _assemble$1(StringBuilder source) {
//    source.append("<definition assembly=\"contents.fully.qualified\" version=\"1.0\">\n");
//    source.append("\n");
//    source.append("  <boolean name=\"com.amazon.ata.customerservice#isParent\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#isParent\">\n");
//    source.append("    <name value=\"isParent\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#isParent\">\n");
//    source.append("    <class value=\"java.lang.Boolean\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <boolean name=\"com.amazon.ata.customerservice#isAlive\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#isAlive\">\n");
//    source.append("    <name value=\"isAlive\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#isAlive\">\n");
//    source.append("    <class value=\"java.lang.Boolean\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#errorMessage\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#errorMessage\">\n");
//    source.append("    <name value=\"errorMessage\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#errorMessage\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#InvalidParameterException\" isa=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <type value=\"BadArgs\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"InvalidParameterException:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <name value=\"InvalidParameterException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.InvalidParameterException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"InvalidParameterException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#InvalidParameterException\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.InvalidParameterException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <member name=\"message\" target=\"com.amazon.ata.customerservice#errorMessage\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <fault target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("  </fault>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.customerservice#DependencyException\"><![CDATA[\n");
//    source.append("        This exception is thrown on a database (or other dependency) error\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <type value=\"ServiceFailure\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <class value=\"DependencyException:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <name value=\"DependencyException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.DependencyException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <senderfault value=\"false\"/>\n");
//    source.append("    <code value=\"DependencyException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#DependencyException\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.DependencyException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerProfile$homeState\">\n");
//    source.append("    <name value=\"homeState\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#CustomerProfile$homeState\">\n");
//    source.append("    <name value=\"homeState\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#CustomerProfile$homeState\">\n");
//    source.append("    <name value=\"homeState\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#CustomerProfile$homeState\">\n");
//    source.append("    <name value=\"homeState\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#CustomerProfile$homeState\">\n");
//    source.append("    <order value=\"2\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <member name=\"ageRange\" target=\"com.amazon.ata.customerservice#AgeRange\"/>\n");
//    source.append("    <member name=\"parent\" target=\"com.amazon.ata.customerservice#isParent\"/>\n");
//    source.append("    <member name=\"homeState\" target=\"com.amazon.ata.customerservice#State\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <name value=\"CustomerProfile\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.CustomerProfile\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <class value=\"CustomerProfile:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#CustomerProfile\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.CustomerProfile\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#Token\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#Token\">\n");
//    source.append("    <name value=\"Token\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#Token\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerProfile$ageRange\">\n");
//    source.append("    <name value=\"ageRange\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#CustomerProfile$ageRange\">\n");
//    source.append("    <name value=\"ageRange\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#CustomerProfile$ageRange\">\n");
//    source.append("    <name value=\"ageRange\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#CustomerProfile$ageRange\">\n");
//    source.append("    <name value=\"ageRange\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#CustomerProfile$ageRange\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"Message\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#ClientFaultException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#ClientFaultException$message\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#customerId\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#customerId\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#Category\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <enumjava target=\"com.amazon.ata.customerservice#Category\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.Category\"/>\n");
//    source.append("  </enumjava>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#Category\">\n");
//    source.append("    <name value=\"Category\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <enum target=\"com.amazon.ata.customerservice#Category\">    <enumValue value=\"PRIME_VIDEO\" name=\"PRIME_VIDEO\"/>    <enumValue value=\"AMAZON_MUSIC\" name=\"AMAZON_MUSIC\"/>    <enumValue value=\"KINDLE\" name=\"KINDLE\"/>    <enumValue value=\"ECHO\" name=\"ECHO\"/>    <enumValue value=\"FRESH\" name=\"FRESH\"/>    <enumValue value=\"TECHNICAL_BOOKS\" name=\"TECHNICAL_BOOKS\"/>    <enumValue value=\"CHILDRENS_BOOKS\" name=\"CHILDRENS_BOOKS\"/>    <enumValue value=\"MAGAZINES\" name=\"MAGAZINES\"/>    <enumValue value=\"VIDE");
//    source.append("O_GAMES\" name=\"VIDEO_GAMES\"/>    <enumValue value=\"ELECTRONICS\" name=\"ELECTRONICS\"/>    <enumValue value=\"COMPUTERS\" name=\"COMPUTERS\"/>    <enumValue value=\"HOME\" name=\"HOME\"/>    <enumValue value=\"PET\" name=\"PET\"/>  </enum>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#Category\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <member name=\"customerId\" target=\"com.amazon.ata.customerservice#customerId\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <name value=\"GetCustomerProfileRequest\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.GetCustomerProfileRequest\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <class value=\"GetCustomerProfileRequest:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerProfileRequest\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <httplabel target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <label value=\"marketplaceId\"/>\n");
//    source.append("  </httplabel>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$marketplaceId\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("    <name value=\"usdSpent\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("    <name value=\"usdSpent\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("    <name value=\"usdSpent\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("    <name value=\"usdSpent\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#Spend$usdSpent\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#AgeRange\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <enumjava target=\"com.amazon.ata.customerservice#AgeRange\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.AgeRange\"/>\n");
//    source.append("  </enumjava>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#AgeRange\">\n");
//    source.append("    <name value=\"AgeRange\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <enum target=\"com.amazon.ata.customerservice#AgeRange\">    <enumValue value=\"UNDER_18\" name=\"UNDER_18\"/>    <enumValue value=\"AGE_18_TO_21\" name=\"AGE_18_TO_21\"/>    <enumValue value=\"AGE_22_TO_25\" name=\"AGE_22_TO_25\"/>    <enumValue value=\"AGE_26_TO_30\" name=\"AGE_26_TO_30\"/>    <enumValue value=\"AGE_31_TO_35\" name=\"AGE_31_TO_35\"/>    <enumValue value=\"AGE_36_TO_45\" name=\"AGE_36_TO_45\"/>    <enumValue value=\"AGE_46_TO_60\" name=\"AGE_46_TO_60\"/>    <enumValue value=\"OVER_60\" name=\"OVER_60\"/>  </en");
//    source.append("um>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#AgeRange\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <httplabel target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <label value=\"customerId\"/>\n");
//    source.append("  </httplabel>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest$customerId\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#SpendCategories$value\">\n");
//    source.append("    <name value=\"value\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#SpendCategories$value\">\n");
//    source.append("    <name value=\"value\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <integer name=\"com.amazon.ata.customerservice#usdSpent\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#usdSpent\">\n");
//    source.append("    <name value=\"usdSpent\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#usdSpent\">\n");
//    source.append("    <class value=\"int\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("    <name value=\"customerSpendCategories\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("    <name value=\"customerSpendCategories\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("    <name value=\"customerSpendCategories\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("    <name value=\"customerSpendCategories\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse$customerSpendCategories\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("    <name value=\"spendCategories\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("    <name value=\"spendCategories\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("    <name value=\"spendCategories\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("    <name value=\"spendCategories\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#CustomerSpendCategories$spendCategories\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#State\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <enumjava target=\"com.amazon.ata.customerservice#State\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.State\"/>\n");
//    source.append("  </enumjava>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#State\">\n");
//    source.append("    <name value=\"State\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <enum target=\"com.amazon.ata.customerservice#State\">    <enumValue value=\"AL\" name=\"AL\"/>    <enumValue value=\"AK\" name=\"AK\"/>    <enumValue value=\"AZ\" name=\"AZ\"/>    <enumValue value=\"AR\" name=\"AR\"/>    <enumValue value=\"CA\" name=\"CA\"/>    <enumValue value=\"CO\" name=\"CO\"/>    <enumValue value=\"CT\" name=\"CT\"/>    <enumValue value=\"DE\" name=\"DE\"/>    <enumValue value=\"FL\" name=\"FL\"/>    <enumValue value=\"GA\" name=\"GA\"/>    <enumValue value=\"HI\" name=\"HI\"/>    <enumValue value=\"ID\" name=\"ID\"/>   ");
//    source.append(" <enumValue value=\"IL\" name=\"IL\"/>    <enumValue value=\"IN\" name=\"IN\"/>    <enumValue value=\"IA\" name=\"IA\"/>    <enumValue value=\"KS\" name=\"KS\"/>    <enumValue value=\"KY\" name=\"KY\"/>    <enumValue value=\"LA\" name=\"LA\"/>    <enumValue value=\"ME\" name=\"ME\"/>    <enumValue value=\"MD\" name=\"MD\"/>    <enumValue value=\"MA\" name=\"MA\"/>    <enumValue value=\"MI\" name=\"MI\"/>    <enumValue value=\"MN\" name=\"MN\"/>    <enumValue value=\"MS\" name=\"MS\"/>    <enumValue value=\"MO\" name=\"MO\"/>    <enumValue value=\"M");
//    source.append("T\" name=\"MT\"/>    <enumValue value=\"NE\" name=\"NE\"/>    <enumValue value=\"NV\" name=\"NV\"/>    <enumValue value=\"NH\" name=\"NH\"/>    <enumValue value=\"NJ\" name=\"NJ\"/>    <enumValue value=\"NM\" name=\"NM\"/>    <enumValue value=\"NY\" name=\"NY\"/>    <enumValue value=\"NC\" name=\"NC\"/>    <enumValue value=\"ND\" name=\"ND\"/>    <enumValue value=\"OH\" name=\"OH\"/>    <enumValue value=\"OK\" name=\"OK\"/>    <enumValue value=\"OR\" name=\"OR\"/>    <enumValue value=\"PA\" name=\"PA\"/>    <enumValue value=\"RI\" name=\"RI\"/>    <e");
//    source.append("numValue value=\"SC\" name=\"SC\"/>    <enumValue value=\"SD\" name=\"SD\"/>    <enumValue value=\"TN\" name=\"TN\"/>    <enumValue value=\"TX\" name=\"TX\"/>    <enumValue value=\"UT\" name=\"UT\"/>    <enumValue value=\"VT\" name=\"VT\"/>    <enumValue value=\"VA\" name=\"VA\"/>    <enumValue value=\"WA\" name=\"WA\"/>    <enumValue value=\"WV\" name=\"WV\"/>    <enumValue value=\"WI\" name=\"WI\"/>    <enumValue value=\"WY\" name=\"WY\"/>  </enum>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#State\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("    <name value=\"numberOfPurchases\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("    <name value=\"numberOfPurchases\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("    <name value=\"numberOfPurchases\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("    <name value=\"numberOfPurchases\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#Spend$numberOfPurchases\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <operation name=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\">\n");
//    source.append("    <input target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\"/>\n");
//    source.append("    <output target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.customerservice#InvalidParameterException\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.customerservice#DependencyException\"/>\n");
//    source.append("  </operation>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\">\n");
//    source.append("    <name value=\"GetCustomerSpendCategories\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\"><![CDATA[\n");
//    source.append("        Get the categories a customer has spent money in and how much money they have spent in the trailing 6 months.\n");
//    source.append("        This data is refreshed daily.\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <http target=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\">\n");
//    source.append("    <httpresponsecode value=\"200\"/>\n");
//    source.append("    <verb value=\"GET\"/>\n");
//    source.append("    <uri value=\"customerSpendCategories/{marketplaceId}/{customerId}\"/>\n");
//    source.append("  </http>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerSpendCategoriesActivity\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <integer name=\"com.amazon.ata.customerservice#numberOfPurchases\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#numberOfPurchases\">\n");
//    source.append("    <name value=\"numberOfPurchases\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#numberOfPurchases\">\n");
//    source.append("    <class value=\"int\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <httplabel target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <label value=\"customerId\"/>\n");
//    source.append("  </httplabel>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <name value=\"customerId\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest$customerId\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#DependencyException$message\">\n");
//    source.append("    <name value=\"Message\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#DependencyException$message\">\n");
//    source.append("    <name value=\"message\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#DependencyException$message\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <member name=\"customerSpendCategories\" target=\"com.amazon.ata.customerservice#CustomerSpendCategories\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <name value=\"GetCustomerSpendCategoriesResponse\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.GetCustomerSpendCategoriesResponse\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <class value=\"GetCustomerSpendCategoriesResponse:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesResponse\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerSpendCategoriesResponse\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerProfile$parent\">\n");
//    source.append("    <name value=\"parent\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#CustomerProfile$parent\">\n");
//    source.append("    <name value=\"parent\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#CustomerProfile$parent\">\n");
//    source.append("    <name value=\"parent\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#CustomerProfile$parent\">\n");
//    source.append("    <name value=\"parent\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#CustomerProfile$parent\">\n");
//    source.append("    <order value=\"1\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <string name=\"com.amazon.ata.customerservice#marketplaceId\" encoding=\"utf-8\"/>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#marketplaceId\">\n");
//    source.append("    <name value=\"marketplaceId\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#marketplaceId\">\n");
//    source.append("    <class value=\"java.lang.String\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <member name=\"spendCategories\" target=\"com.amazon.ata.customerservice#SpendCategories\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <name value=\"CustomerSpendCategories\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.CustomerSpendCategories\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <class value=\"CustomerSpendCategories:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#CustomerSpendCategories\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.CustomerSpendCategories\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <member name=\"customerProfile\" target=\"com.amazon.ata.customerservice#CustomerProfile\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <name value=\"GetCustomerProfileResponse\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.GetCustomerProfileResponse\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <class value=\"GetCustomerProfileResponse:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerProfileResponse\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("    <name value=\"customerProfile\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <javaname target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("    <name value=\"customerProfile\"/>\n");
//    source.append("  </javaname>\n");
//    source.append("\n");
//    source.append("  <jsonname target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("    <name value=\"customerProfile\"/>\n");
//    source.append("  </jsonname>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("    <name value=\"customerProfile\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <xmlorder target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("    <order value=\"0\"/>\n");
//    source.append("  </xmlorder>\n");
//    source.append("\n");
//    source.append("  <required target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse$customerProfile\">\n");
//    source.append("  </required>\n");
//    source.append("\n");
//    source.append("  <service name=\"com.amazon.ata.customerservice#ATACustomerService\">\n");
//    source.append("    <operation target=\"com.amazon.ata.customerservice#GetCustomerSpendCategories\"/>\n");
//    source.append("    <operation target=\"com.amazon.ata.customerservice#GetCustomerProfile\"/>\n");
//    source.append("  </service>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.customerservice#ATACustomerService\"><![CDATA[\n");
//    source.append("        An example service, deployed with the Octane Service creator,\n");
//    source.append("        which will query and manipulate a set of beer information\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#ATACustomerService\">\n");
//    source.append("    <name value=\"ATACustomerService\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#ATACustomerService\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.ATACustomerService\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <map name=\"com.amazon.ata.customerservice#SpendCategories\">\n");
//    source.append("    <key target=\"com.amazon.ata.customerservice#Category\"/>\n");
//    source.append("    <value target=\"com.amazon.ata.customerservice#Spend\"/>\n");
//    source.append("  </map>\n");
//    source.append("\n");
//    source.append("  <xmlartificial target=\"com.amazon.ata.customerservice#SpendCategories\">\n");
//    source.append("    <name value=\"entry\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"true\"/>\n");
//    source.append("  </xmlartificial>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#SpendCategories\">\n");
//    source.append("    <name value=\"SpendCategories\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#SpendCategories\">\n");
//    source.append("    <class value=\"java.util.Map\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <member name=\"numberOfPurchases\" target=\"com.amazon.ata.customerservice#numberOfPurchases\"/>\n");
//    source.append("    <member name=\"usdSpent\" target=\"com.amazon.ata.customerservice#usdSpent\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <name value=\"Spend\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.Spend\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <class value=\"Spend:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#Spend\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.Spend\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#ClientFaultException\" abstract=\"true\">\n");
//    source.append("    <member name=\"message\" target=\"com.amazon.ata.customerservice#errorMessage\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <exception target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("  </exception>\n");
//    source.append("\n");
//    source.append("  <awssoap11error target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"500\"/>\n");
//    source.append("  </awssoap11error>\n");
//    source.append("\n");
//    source.append("  <bsferror target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <type value=\"BadArgs\"/>\n");
//    source.append("  </bsferror>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <class value=\"ClientFaultException:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <name value=\"ClientFaultException\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.ClientFaultException\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <awssoap12error target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </awssoap12error>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <httperror target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("  </httperror>\n");
//    source.append("\n");
//    source.append("  <awsqueryerror target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <senderfault value=\"true\"/>\n");
//    source.append("    <code value=\"ClientFaultException\"/>\n");
//    source.append("    <httpresponsecode value=\"400\"/>\n");
//    source.append("    <allowadditionalfields value=\"false\"/>\n");
//    source.append("  </awsqueryerror>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#ClientFaultException\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.ClientFaultException\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <structure name=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <member name=\"customerId\" target=\"com.amazon.ata.customerservice#customerId\"/>\n");
//    source.append("    <member name=\"marketplaceId\" target=\"com.amazon.ata.customerservice#marketplaceId\"/>\n");
//    source.append("  </structure>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <name value=\"GetCustomerSpendCategoriesRequest\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsf target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <class value=\"amazon.ata.customerservice.GetCustomerSpendCategoriesRequest\"/>\n");
//    source.append("  </bsf>\n");
//    source.append("\n");
//    source.append("  <jsontypefield target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <name value=\"__type\"/>\n");
//    source.append("  </jsontypefield>\n");
//    source.append("\n");
//    source.append("  <wrapper target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <output value=\"false\"/>\n");
//    source.append("    <input value=\"false\"/>\n");
//    source.append("  </wrapper>\n");
//    source.append("\n");
//    source.append("  <json target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <class value=\"GetCustomerSpendCategoriesRequest:http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("  </json>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerSpendCategoriesRequest\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerSpendCategoriesRequest\"/>\n");
//    source.append("  </java>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#SpendCategories$key\">\n");
//    source.append("    <name value=\"key\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <bsfname target=\"com.amazon.ata.customerservice#SpendCategories$key\">\n");
//    source.append("    <name value=\"key\"/>\n");
//    source.append("  </bsfname>\n");
//    source.append("\n");
//    source.append("  <operation name=\"com.amazon.ata.customerservice#GetCustomerProfile\">\n");
//    source.append("    <input target=\"com.amazon.ata.customerservice#GetCustomerProfileRequest\"/>\n");
//    source.append("    <output target=\"com.amazon.ata.customerservice#GetCustomerProfileResponse\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.customerservice#InvalidParameterException\"/>\n");
//    source.append("    <error target=\"com.amazon.ata.customerservice#DependencyException\"/>\n");
//    source.append("  </operation>\n");
//    source.append("\n");
//    source.append("  <xml target=\"com.amazon.ata.customerservice#GetCustomerProfile\">\n");
//    source.append("    <name value=\"GetCustomerProfile\"/>\n");
//    source.append("    <namespace value=\"http://internal.amazon.com/coral/com.amazon.ata.customerservice/\"/>\n");
//    source.append("    <nillable value=\"false\"/>\n");
//    source.append("  </xml>\n");
//    source.append("\n");
//    source.append("  <documentation target=\"com.amazon.ata.customerservice#GetCustomerProfile\"><![CDATA[\n");
//    source.append("        Get a profile for the customer.  Customer profiles' contain information about a customer's demographic\n");
//    source.append("        information.\n");
//    source.append("    ]]></documentation>\n");
//    source.append("\n");
//    source.append("  <http target=\"com.amazon.ata.customerservice#GetCustomerProfile\">\n");
//    source.append("    <httpresponsecode value=\"200\"/>\n");
//    source.append("    <verb value=\"GET\"/>\n");
//    source.append("    <uri value=\"customerProfile/{customerId}\"/>\n");
//    source.append("  </http>\n");
//    source.append("\n");
//    source.append("  <java target=\"com.amazon.ata.customerservice#GetCustomerProfile\">\n");
//    source.append("    <class value=\"com.amazon.ata.customerservice.GetCustomerProfileActivity\"/>\n");
//    source.append("  </java>\n");
//  }
//
//  private static void _assemble$2(StringBuilder source) {
//    source.append("\n");
//    source.append("</definition>");
//  }
//
//}
